language: node_js
sudo: false
dist: trusty
node_js:
- 6
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=production
install:
- npm --production=false install
- npm --production=false update
jobs:
    include:
        - script: npm test
        - stage: deploy
          script: npm run build
          before_deploy:
            - git config --global user.email $(git log --pretty=format:"%ae" -n1)
            - git config --global user.name $(git log --pretty=format:"%an" -n1)
          deploy:
            - provider: script
              on:
                all_branches: true
                condition: $TRAVIS_BRANCH != master
              skip_cleanup: true
              script: npm run deploy -- -e $TRAVIS_BRANCH -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
            - provider: script
              on:
                branch: master
              skip_cleanup: true
              script: npm run deploy -- -a -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
